<div class="row">
  <div class="col">
    <h1>Fala bruxão!</h1>  
  </div>
  <div class="col">
    <?php
      echo "Eh noi que voa!";
    ?>  
  </div>
  <div class="col">
    <ul>
      <?php
        foreach($this->view->dados as $key => $produto) {  
          if($key % 2 == 0) {
            echo "<li class='redlista'>$produto</li>";
          } else {
            echo "<li class='bluelista'>$produto</li>";
          }
        }
      ?>
    </ul>
  </div>
</div>
