<main>
    <div class="container-fluid">
        <h1 class="mt-4">Navegando Via Dropdown</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Navegando Via Dropdown</li>
        </ol>
        <div class="card mb-4">
            <div class="card-body">
                <p class="mb-0">
                    This page is an example of using dropdown navigation. O resto é só balela By removing the
                    <code>.sb-nav-fixed</code>
                    class from the
                    <code>body</code>
                    , the top navigation and side navigation will become static on scroll. Scroll down this page to see an example.
                </p>
            </div>
        </div> 
    </div>
</main>
        